sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - node

script: yarn run ci

after_success: yarn run ci:coverage

# use build stages with "test" and "deploy" stages
# node_js versions above automatically added to "test" stage
jobs:
  include:
    # TODO(mc, 2018-04-13): add browser test to default "test" stage
    # - script: yarn run test:browser
    #   node_js: node

    - stage: deploy
      # deploy if tag starts with v
      if: tag =~ ^v
      node_js: node
      script: yarn run example && yarn run docs
      after_success: echo "skipping coverage upload"
      # set npm credentials for npm publish
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
      deploy:
        provider: script
        script: npm run publish
        # keep node_modules for deploy
        skip_cleanup: true
        # deploy on tagged commits
        on:
          repo: tracespace/tracespace
          tags: true
          all_brances: true

cache: yarn
