# tracespace/tracespace TravisCI configuration

language: node_js

# lts/carbon used as default in explicit job entries
node_js:
  - 'lts/carbon'
  - 'lts/dubnium'
  - node

script:
  - npm test
  - npm run coverage:upload

cache:
  npm: true

_deploy_base: &_deploy_base
  provider: script
  skip_cleanup: true
  on:
    repo: tracespace/tracespace
    all_branches: true

# use build stages with "test" and "deploy" stages
# jobs for node_js versions above automatically added to matrix "test" stage
jobs:
  include:
    - # test that app builds all work
      stage: test
      name: 'App builds'
      script: npm run build

    - # package deploy to npm on tagged commits
      if: tag =~ ^v
      stage: deploy
      name: 'Deploy packages to npm'
      script: npm run example && npm run docs
      # set npm credentials for npm publish
      before_deploy:
        - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        - export NPM_TAG=$(node scripts/get-npm-tag.js $TRAVIS_TAG)
      deploy:
        <<: *_deploy_base
        script: npm run publish:npm

    - # apps deploy to s3 on next (staging) and tagged commits (production)
      # TODO(mc, 2019-03-05): update "next" to "master" for 4.0.0
      if: tag =~ ^v OR (branch = next AND type != pull_request)
      stage: deploy
      name: 'Deploy apps to s3'
      script: npm run build
      # set bucket for deploy
      # TODO(mc, 2019-03-05): update "next" to "master" for 4.0.0
      before_deploy:
        - |
          if [ $TRAVIS_BRANCH = next ]; then
            export AWS_S3_BUCKET=$AWS_S3_BUCKET_STAGING
          else
            export AWS_S3_BUCKET=$AWS_S3_BUCKET_PRODUCTION
          fi
      deploy:
        <<: *_deploy_base
        script: npm run publish:s3
