# tracespace/tracespace TravisCI configuration

language: node_js

# lts/carbon used as default in explicit job entries
node_js:
  - 'lts/carbon'
  - 'lts/dubnium'
  - node

script:
  - npm test
  - npm run coverage:upload

cache:
  npm: true

_deploy_base: &_deploy_base
  provider: script
  skip_cleanup: true
  on: &_deploy_base__on
    repo: tracespace/tracespace
    all_branches: true

# use build stages with "test" and "deploy" stages
# jobs for node_js versions above automatically added to matrix "test" stage
jobs:
  include:
    - # test that app builds all work
      stage: test
      name: App builds
      script: npm run build

    - # build and publish
      if: tag =~ ^v OR (branch = master AND type != pull_request)
      stage: deploy
      name: Deploy to npm and s3
      script: npm run build
      before_deploy:
        # set npm deploy parameters
        - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        - export NPM_TAG=$(node scripts/get-npm-tag.js $TRAVIS_TAG)
        # set s3 deploy parameters
        - |
          if [ $TRAVIS_BRANCH = master ]; then
            export AWS_S3_BUCKET=$AWS_S3_BUCKET_STAGING
          else
            export AWS_S3_BUCKET=$AWS_S3_BUCKET_PRODUCTION
          fi
      deploy:
        - # s3 publish on master (staging) and tagged commits (production)
          <<: *_deploy_base
          script: npm run publish:s3

        - # npm publish on tags only
          <<: *_deploy_base
          script: npm run publish:npm
          on:
            <<: *_deploy_base__on
            tags: true
