sudo: false
language: node_js
node_js:
- '0.10'
- '4'
- node
matrix:
  include:
  - node_js: node
    env: TEST_BROWSERS=true
script: npm run-script ci
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: Ub9TdnUkapMFBK9kKfoEC7JGm1QRNvaggV2gbRAmAzZYJUwmbvvUqOBEDLpLEserqw0aCcv9Vmxlhv6gui1ZUT+5asiDu2P2I/QI9oLCwPzdk3pF8x/yv7aOQvW37oAtQ60futdN9WLTNY/tQ42xWckyMyCOFYicCI+VRj92yM6A0orS74UeNHIW22ssxn8r98cTkfOVDG+Ze+uL/qvmC1a0wsrd2qscSc9hLTO04UhBgqDulJFE0w2TArsArPW82McIqRiI1jhcjCqxVVfiiWpJiASvPUb2E7DK9WQ8yLOjDYjeMqLrjzKJlWSG5yZedoa2245Nd/gLUALf8YnhqeXL7UYIDbD1WtQNVdXZSrPux5D+oBH4M9By33NsXn8hgElr5UEm2oArTbpiophvmh1yGCjkQAOARBp9Ki6B/hb0YLQVyzF/vBkb/v1aiyiRPqBIE8A+cBggB5MqGkhvTAyV+rbqJ/Y/oFen0Q1NXxfDH6z0BsNgRSSJp/LK4wZnV6dHwGwb0zt6fjJTD7iWTMIqp+6RItkZrtu//Y8dMfJdA5vUYLkYZV4qSpaCgxB3RJBm1s+2lLgWxlvEQ5PnbsaGbS52zaBh7vKRHyuSQlhMxsCSjwIu697SK5rfn6pvGAW6XQrhAvLUcAoPTpC+sSaZanEWxaIhfwzfiQXuolE=
  on:
    node: node
    tags: true
    condition: "$TEST_BROWSERS = true"
    all_branches: true
env:
  global:
  - secure: 4QCfi+3tEU7GkP/oR1lk6UHPWiITTbweLy0dXOCTAhTCUBw9YB6txNl79fIiFuO0pcxMJ8gZ7KUEnJlFpkw6wlslLIKP0N481Kqxf/8q49R10Z29zAEDRInWTjNDQKx6mPOHv3elQEZGhRQI+LLWNR0UMTEbyYiabGgc/WHBAcSh8t05yfdMMt7bksrRkMfB8/XuGtx216gVmo8jUhMvQ55VJzp/lsvnrRB5gtBMKUBYKLV7zMaAp4sgvJUm2nlzblzbce31MkAzlwD8BpC5b+z1wwQwnZliITbVU6YkmKV96ljSocUqeC5628dDJAx5DBr8lJIbwf371vTbwWFW5nU6nAlKL5WrAEvlk4gWeH9qP8/GFZ75k2HiE1Czn6yj4CbqEdtBNLhckIJ0/OdMbr14qGMYZ38JXyJy6fLomv5M+HM3ml/AKyds8NafOF61F3Zh22E5zsy6gTXSe1ZnDfW/JypRddRWXhFSdmBm63VXGx6y/Gc0NarOCCJaFhGm1QLDc3TKB1mWB2KdHkPjxDSXxfaSTaV5QMii/o68wu1GfDk1EPjVBfKEhNJfPazfTxUP/hLc8Ld9pqE5igtFcelRc8elsd0tUtiNUVV9TRlFWo4gauHzXBHvteR4Fk+2XH1A3TNMOJ/YqeDpb6Klvk+j3xSAvxnKz49Ym28yvco=
  - secure: rKxuy4Mx9eONu6JtZHj0C4NK1cOZm1aRCJyYio3pyFuOzPGQmLM+T7Sb2EYuMpIG5MCk8GYL9e+Ij0d3ZqYBXCa/qIkKTYvoCajnkXHbMShBGrCPqXfjPe3zydVxL0kL1YTUaXwUPw7qWoWmE4YdYgnaWajW3Wx+Xrbh4LU3yVAAGwdaqQl2RDeXtA/R+phCq7untFNz9AHmyJqUNJdjzjgX4SdgixVKG+S6nLmPpf8nKyZ4QrnTGPUuZs9fRbZkAkre1KsFdGo5u61/w7vgVX3S2jZLslqKaIEuL2NvWXBpWGjsZLt+pFswHam2pJ10UNmCDS2Wg/jer1YTjdrHhddkJ8GnvG/rKFj8NzOzk0iYZubjd6NMqdutOXcEZbDLERYsdsBMfbyXch+s8RV1NFiMdY6Tip+4kr0v23REFGBDBoiK8NPjjwUhLQ2a/HExmUHDEMTHhSVyeoR6uS1WSRVnwBbagVxar78lOC7N2BUBvPPs90SK3FSeph3FoglHTWPy1A99ibeNfOWXEKi0iyi2iUsBjjrbuywrZeF89EwXsaoQu3PM5Cc2t/nt66c9z20s951lSRYVnPeooXVfp0S0TDrS6WDjeS77xqqpMDHRdcJVwBXw2+yGvXY0T/UDpp+DeOorwMhKkEQINb4BjUYkow2xdNxmHqIIy4YQmXA=
  - secure: lWx9cAUI4+MCaY219WMKd+27Z44SvdaLA5ArOmLuqCNqMQXDFTXo3yRF8/bye31gsVi+7vQiGPQEt6fkm4toZJ2js8CzDOWShvy5o3bW4b2yO69EG81JUjiQfuBzKyuB77HcGefPb0ZpklMNOBIZI/ra4+473/Va/4Sq5598R3rrWqmkqa+IDv7Oa1aSv1mxt4oon7VkGGuI5aQhVMCdvFtC0lNpyBB5pmt9foZ4VeSLJ0R1NksCEjhjIOiJPvhbuAfZMtwPDEanqcMsC5PG9fhuZSnELHx8kMgjT8NNVlcXzcsgmnQ+/6j6Wh9rvLzF3JWpPtHX5xmDDSaWyk1QF3EFpryyEsxV04Iis7GXmVTkz9hmuWm43XV3bubIR8utjTGGtWx5d5YvaUNI5NxB3s5YAw17fjV6THWnNRWvcvC6oN1nqV/tTXE7B64LEGr95EdLxIJACr6/tZhFFXgbJozq4U1Mf3RM6ZmTmCvaBMSYEobqGd/nzqxtwNUmUMqzJGduQn0d/XJbZxUdnk5jf7b+RSulqIoTqUr8aN2EfDUTyWlAfmB8A3KzSiQeUDbn12B8092vF1+Wma6jtdY6GSI4Tyq+U44CiOSK5QNl///tvpT7FgvjddwbgtebgUxq3+Cw+3Tr+DiYn+tcRUAa0qHaM1xyZX3/6AQcTeXZM6Y=
