ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: firefox
    version: [-1..46]
  - name: ie
    version: -1..latest
  - name: microsoftedge
    version: latest
browserify:
  - plugin: proxyquire-universal
concurrency: 4
tunnel:
  type: ngrok
  bind_tls: true
