ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: latest
  - name: opera
    version: latest
browserify:
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .coffee
