name: tracespace ci
on: [push]

defaults:
  runs-on: ubuntu-latest

jobs:
  test:
    name: unit tests
    strategy:
      matrix:
        node-version: ['10', '12', '14']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - uses: codecov/codecov-action@v1

  lint:
    name: lint and format checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn format --check

  build:
    name: build assets and type definitions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn build:all
