name: continuous integration
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: ['14', '16', '18']
    name: unit tests on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
        with:
          version: '7.0.0'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:once
      - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
        with:
          files: coverage/coverage-final.json

  check:
    name: format, lint, and build checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
        with:
          version: '7.0.0'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
